remote_theme: liminalproperty/dinky
title: Linaker Street Property Ltd
show_downloads: false
legalfooter: >
  Linaker Street Property Ltd is a company registered in England & Wales.
  Company number: 16274828.  Registered address: Flat 3, 16 The Ridgeway,
  Enfield, EN2 8QH
